- .gitignore
- Gruntfile.js
- TESTING.md
- options.js
- pacer.js
- spec/PacerSpec.js
These are far from complete, but I thought I should commit them and create a Pull Request to make sure there is buy-in for the general methodology.
Note that the extra files like the Gruntfile and the contents of the `spec` folder, will get pulled into the built extension. However, as far as I can tell they have no effect, as expected.
> First round of Jasmine tests

- pacer.js
- spec/PacerSpec.js
I added tests for the remaining methods. Also cleaned up some of the methods under test to return proper booleans, similar to what was done in the previous CL.
Thanks!
> Add remaining tests for the static PACER methods.

- .travis.yml
- package.json
We've got unit tests now, why not run them on every push?
> Add Travis-CI support

- content.js
- content_delegate.js
- spec/ContentDelegateSpec.js
This is the final stage of the ambitious refactor of content.js. Now, instead of the content script being run and a bunch of naked functions and if statements being executed, the content script delegates to ContentDelegate, which means that the functionality of the content script is testable (and a sizable number of tests have been added).
In #25, we added a logging method to see if there were any so-called "convertible document URLs" that people were encountering in the wild. It turns out there's plenty of them. The RECAP chrome extension, when it encounters one of these, goes through a big dance to get the doc1/ style URL of the document, then finally uploads metadata for the document. Presumably this is to capture the docid, which might otherwise be unavailable if the document was …
> Refactor and test the handling of convertible document URLs and adding RECAP links

- background.js
- content.js
- content_delegate.js
- notifier.js
- recap.js
Also console.debug(), etc. Don't be one of those bad extensions where
you can't figure out who is sourcing the messages. Maybe there should
be a helper function, but that gets tricky because of the background
scope, so just do it the easy way for now.
> Be polite. Every console.log() invokation should say "RECAP:"

- content_delegate.js
- manifest.json
- pacer.js
- recap.js
- utils.js
A variety of improvements that are on the way to appellate support, including parsing of caseids from URLs, adding some comments/questions, removing unnecessarily web-accessible js assets, relaxing the doc1 link regexp, etc.
> Parsing improvements

- spec/PacerSpec.js
Instructions at the point of need, as Tufte would [say](https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0001HD). That is, put strings where we use them, where feasible.
> Improve PacerSpec.js readability

- content_delegate.js
- pacer.js
Do not upload restricted documents, per freelawproject/recap#264
Needs review and probable partial squashing.
> 2019.01.24.restricted warnings

- manifest.json
> issue-260-search fix name

- spec/PacerSpec.js
Added tests for getDocumentIdFromForm and getCaseNumberFromInputs as primary task. Reordered other test groups to match order of the functions in pacer.js. Added additional explicit tests for things that already had some code coverage through other testing.
Changed from removing the innerHTML of some fixtures to removing them completely. The removal will aide in preparations for being able to execute tests in random order as it doesn't leave the testing document cluttered with the setups for tests that have already been run. Cleanup of the other two Spec files will be needed in this regard.
> test(PacerSpec.js): 100% code coverage, tests in order, fixture cleanup

- src/options.html
set language
attached labels to inputs in unused section
added alt tags to images
> fix(options.html): fix accessibility

- src/content_delegate.js
Fix for https://github.com/freelawproject/recap/issues/277
> FIX for RECAP fails to load documents for Northern District of Georgia #277

- .eslintrc.js
- package-lock.json
- package.json
- src/background.js
- src/content.js
- src/content_delegate.js
- src/notifier.js
- src/options.js
- src/pacer.js
- src/recap.js
- src/toolbar_button.js
Hey folks,
This is the start of a cleanup branch.  gonna get some JS linting configs up in here.
Thoughts/feelings/etc would be appreciated!  (the obvious changes here are replacing string concat with template strings and other typo-proofing)
> Cleanup PR

- spec/ContentDelegateSpec.js
- src/background.js
- src/content_delegate.js
- src/options.html
- src/options.js
- src/toolbar_button.js
For @mlissner to check over (and run the tests)
> Invert the polarity of the enabled/disabled switch.

- .travis.yml
- src/content_delegate.js
Resetting the PR to the initial fix. This should fail due to the matchAll issue, but we can debug from there.
> Minimal WV Zip Fix

- src/content_delegate.js
Fix Firefox
An incorrect mathematical calculation killed Firefox
> fix(content-delegate): Firefox fix

- CHANGES.md
- src/assets/css/style-ios.css
- src/assets/css/style.css
- src/content.js
- src/content_delegate.js
- src/pacer.js
- src/utils.js
Fixes [#309](https://github.com/freelawproject/recap/issues/309)
> feat(recap email): Add advertisement banners for RECAP Email

- CHANGES.md
This PR will update the changes.md file
> docs(security): Update CHANGES.md

- spec/ContentDelegateSpec.js
- src/content_delegate.js
- src/recap.js
- src/utils.js
This PR will fix https://github.com/freelawproject/recap/issues/319
> Fix(content delegate): Document upload missing pacer case id

- CHANGES.md
This PR updates the changes.md file after merging https://github.com/freelawproject/recap-chrome/pull/303
> docs(review links): Changelog update

- CHANGES.md
This PR updates the changes.md file after merging https://github.com/freelawproject/recap-chrome/pull/306
> docs(refresh links button): Changelog update

- CHANGES.md
- src/utils.js
This PR fixes https://github.com/freelawproject/recap/issues/329.
> feat(autofill): uncheck terminates parties

- CHANGES.md
- spec/AppellateSpec.js
- src/appellate/appellate.js
- src/appellate/utils.js
This PR fixes https://github.com/freelawproject/recap/issues/340
> feat(appellate): Add logic to get doc_id from the dls_id parameter

- .github/workflows/check_changelog.yml
- CHANGES.md
This PR updates the release notes and adds a GitHub action to check if a PR includes changes in the `CHANGES.MD` file, so I won't forget to add them next time.
> Update releases notes

- src/content_delegate.js
Refactors the regular expression used to extract ZIP URLs and removes unnecessary capture groups.
> refactor(content_delegate): Tweaks the regex to extract the ZIP URL

- CHANGES.md
- package.json
- src/background.js
- src/manifest.json
This is a small release and we don't yet have the URL working, but @ERosendo, can you give it your :+1: / :-1:, please, and we can merge it if it's ready? 
Once we've got the URL working and we have @jeniferw's approval, we'll do a release in Chrome/Firefox/etc.
> Add donate popup per CL-3416 

- CHANGES.md
- src/options.html
- src/options.js
This PR adds logic to display variants of the new banner component.
> feat(popup): Adds logic to display variants of the banner

- CHANGES.md
- src/content_delegate.js
Fixes:
```
ReferenceError: content is not defined
```
> Fix fetch on firefox

- CHANGES.md
- package.json
- src/manifest.json
> feat(packaging): Do release

- CHANGES.md
- src/utils/background.js
This PR closes https://github.com/freelawproject/recap/issues/384 by implementing functionality to open the donation page in a new tab.
> feat(background): Adds end-of-year pop-up
