utils.js

The real problem that causes #2 is that the server is not returning JSON to a JSON request. Presumably because the server considers it an error.
This PR attempts to fix this by just aborting the ready state change function and not calling the callback. It is assumed that the caller was expecting a parsed JSON data structure and since we are unable to provide that, the callback should be skipped.
To be clear, this simply sidesteps the issue and avoids the stack trace in the console. We still need to investigate why the server is returning such a response and if there is a more appropriate action the extension can take.

Ignore invalid JSON in responses to requests for it.

---

options.js

It looks like normal <a> links don't work in Chrome addon button panes. The link is suppressed somehow and doesn't open anywhere.
This CL makes the link functional by "manually" opening a tab when the link is clicked. The `href` property of the original link is used as the tab destination, so someone editing the HTML doesn't have to think too hard about this process.

Fix donate: use click handler to add new tab when donate link is clicked

---

Gruntfile.js
spec/RecapSpec.js
test/Blob.js
test/mock-ajax.js

Includes test helpers for mocking AJAX in Jasmine and a polyfill for
Blobs in PhantomJS, since the PhantomJS version included by this package
is 1.9 (Blobs are available in 2.0)
See the added tests passing at:
https://travis-ci.org/audiodude/recap-chrome/builds/57119835

Add unit tests for recap.js

---

recap.js
spec/RecapSpec.js

Simply add an empty object with a Jasmine spy, which can act as both a stub and a mock (it's acting as a stub here).

Remove nasty try/catch by using Jasmine spy in tests.

---

Gruntfile.js
content.js
content_delegate.js
manifest.json
spec/ContentDelegateSpec.js
test/mock-utils.js

This is a large complex change, even though it is largely a refactoring and there is supposed to be no changes to the functionality.
The purpose of the change is to make it so that content.js isn't just a top-level script that gets runs on each page that the extension attaches to. The way it was, it was basically untestable, because you had to run the whole script every time.
The refactoring introduces ContentDelegate which is a class that exposes methods that correspond to the methods that previously existed in content.js. Not all functions have been ported over to ContentDelegate in this pass, the more complex PDF uploading functionality will have to be done in a follow up.
To demonstrate the newfound testability of the new class, as well as to help verify that nothing has been broken, …

Refactor content

---

content.js
content_delegate.js
spec/ContentDelegateSpec.js

This PR refactors the part of content.js that is concerned with downloading PDF files, and adds tests for the same.
This part was left for its own PR because of the complexity of the PDF handling code. This code has several nested asynchronous functions. saves entire HTML documents in local variables, manipulates the state of the browser history, and asynchronously downloads then uploads PDF data.
Generally, the strategy employed was to separate the major functionality of this function and extract helper instance methods from several of the embedded functions that were defined inline. To this end, the functions ContentDelegate.showPdfPage and ContentDelegate.onDocumentViewSubmit were created. Liberal use was made of the "bind" browser function in order to assure that the proper object …

Refactor more of content.js and add tests

---

spec/ContentDelegateSpec.js

There were several places that were using the same or similar calls to new ContentDelegate. This change make it more sane that the work is all done in one place, which will make it easier if the signature of the ContentDelegate constructor changes.

Refactor some of the variables in the ContentDelegateSpec to be more sane

---

spec/RecapSpec.js

Based on getting more experience with Jasmine and how to mock built in types, this CL provides a fake FormData psuedo-class that can be used in the already written tests to assert against the values that the recap library is sending to the server.

Uncomment FormData tests and test them using mock/fake FormData objects

---

content.js
recap.js
spec/RecapSpec.js
utils.js

The riskiest part of this change is the slight tweak to utils.js and the send method, so that if the formData is null it is not sent. I clicked around and things seemed to be working.
Otherwise, the gen204 method takes an Object that specifies parameters and does a GET request to the server's gen204 endpoint. I also added the specific event that we wish to log.
Thanks!

Create a gen204 call for logging purposes and its first usage.

---

toolbar_button.js

Address traceback issue raised in (but collateral to) #202.
Only necessary for FF56, but sometimes we can get megaspew (scores) of tracebacks on stderr:
Extension error: TypeError: items.options is undefined moz-extension://0aca09aa-5baf-6545-88c1-9246114796ab/toolbar_button.js 48
[[Exception stack
updateToolbarButton/<@moz-extension://0aca09aa-5baf-6545-88c1-9246114796ab/toolbar_button.js:48:1
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:63:129
runSafeSync@resource://gre/modules/ExtensionUtils.jsm:94:37
runSafe@resource://gre/modules/ExtensionCommon.jsm:164:32
wrapPromise/<@resource://gre/modules/ExtensionCommon.jsm:353:13
]]

toolbar_button.js: Guard items['options']

---

content_delegate.js
pacer.js

Keep regexps on a single line.
Ensure terminal comma on the final line of multiline arrays so future patches are clean.
Ensure statements end in semicolons.
Correct log message from a99f6562f1f646f6508202870035027c70200ede.
Clarify comment regarding Appellate use of caseId.
Consistently use goDLS over goDls (either way we must be consistent. There's a good argument for this one though, I think).
Eliminate unnecessary temp variable.
String.prototype.match() can fail, and when it does, it will cause a TypeError from array destructuring if we don't check. Correct that.
Be smart when destructuring to an object -- don't use a pile of temp vars and repeat them, just destructure into the object directly.
debuglog the source of caseids per discussion at d8754eb#commitcomment-26188087
Match the …

Miscellaneous cleanup from Dec. 11, 2017 commits

---

content_delegate.js

This revises the warning Ka-Ping added in 2013 (02bcc53) to be accurate.
The "courts" do indeed provide document authentication systems. At
bottom, of course, one can redownload the document in PACER, for a
fee, or otherwise obtain it from the Court.
But perhaps more relevantly, CM/ECF does offer a cryptographic hash
service, but it is not useful because: it is restricted by ACL to
filing users only (and is not availble to PACER users who just try the
URL); the hash procedure is not publicly documented; and, at least
superficially, it appears to require a key that is not public
available.
So instead we say there is "no effective document authentication system,"
not "no document authentication system."
<hr>
I seem to recall we had talked about this earlier and potentially the popup was …

content_delegate.js: Narrow scope of auth warning

---

content_delegate.js
pacer.js
spec/PacerSpec.js

Fixes https://github.com/freelawproject/recap/issues/231
Do not assume that `parseGoDLSFunction()` will always be called with a string — it might be called with `null`.
Also ensure all its callers are prepared to deal with failure (false).
Add corresponding tests for these issues.

goDLS() checks

---

content_delegate.js
pacer.js
spec/ContentDelegateSpec.js

Prior to this fix, we'd try to send bankruptcy claim documents to the RECAP Archive. Normally we want all the documents in PACER, but these documents are an example of documents that we *don't* want since they're not even part of the docket. 
I wouldn't normally worry too much about an esoteric type of document on an esoteric type of the legal world (bankruptcy stuff), but this particular bug made it so that the document itself couldn't be downloaded at all. Breaking PACER is not OK, so this fixes that.

Fixes claim doc1 URLs 

---

spec/ContentDelegateSpec.js

According to https://github.com/karma-runner/karma/issues/2652#issuecomment-361682911
someone else had their headless tests break around the same time as us, and `saveAs` was the culprit. Sure enough, mocking this method out fixes them.

Fix tests by mocking out the saveAs method

---

spec/RecapSpec.js

If DEBUG=true is set in recap.js, test should not fail.
Previously, tests of recap endpoints expected uploadDocket() &c. to ~return a result~ **send a request** with debug false.
So if debug is true, tests fail. Boo.
Instead, don't require exact equality in the actualData.
Merely require it to be a superset of the `expected` data, with
jasmine.objectContaining().
@audiodude, can you please review this for sanity?

RecapSpec: Relax tests to allow debugging

---

content.js
install_notifier.js
manifest.json

Pretty basic changes here. All we do is set up the extension to send the version string to any website where it's running and tweak the manifest to send that to a few new places:
- https://www.courtlistener.com
- locahost & 127.0.0.1
- removes the `include_globs` which would normally filter the domain further (this has the side effect of making RECAP work across all of uscourts.gov instead of only on certain domains/urls).
Fixes: freelawproject/recap#215.

feat(recap): Sends the installed version to any URL in the manifest.

---

pacer.js

Better document the appellate regular expression in `isDocketDisplayUrl()`, because there was some confusion about whether it operated properly.
JS has no `(?x)` flag, so we just use a long comment.
xxx: There are three problems with the regexp that become a little
more apparent to me while doing so:
1: It should anchor to `/servlet` rather than just `servlet`
2: `?servlet` need not always be the first parameter
3: it should allow `/TransportRoom/?...` in addition to `/TransportRoom?...`
But this is not a functional change, just a doc fix.

 pacer.js: isDocketDisplayUrl() improve RE documentation

---

manifest.json

Tested adding a search provider for the keyword "recap" to both Chrome and Firefox. The settings page was not altered to add a search input in this request.

issue-260-search Add search features to RECAP extension

---

spec/PacerSpec.js

Only two functions left uncovered: getDocumentIdFromForm and getCaseNumberFromInputs. Those may benefit from an upgrade to karma and jasmine to make testing them easier.

test(PacerSpec.js): increased code coverage from 68% to 76%

---

src/options.html

The RECAP and Donate links in the extension currently don't open anything in Google Chrome (despite working fine in Firefox).  Adding `target="_blank"` is required for Chrome extensions to open new windows.

Fix donate link

---

karma.conf.js
spec/PacerSpec.js
src/pacer.js

This PR solves multiple issues related to the attachment menu page.
- Avoid getting hidden inputs in the query to get the download button:
it seems that some version of CM/ECF uses hidden inputs after the **download button** and the current logic fails to identify the attachment menu event when the button is there. So in order to avoid those undesired elements in the query, this PR adds the type `button` in the CSS selector string used by the `querySelectorAll` method.
- Identify the attachment page for CM/ECF v1.7:
CM/ECF v1.7 uses a different style on the attachment menu page. The current logic fails because the **button** to download the files has a different value. This PR changes the logic that checks the button's value in order to identify the attachment menu in this version.
- …

fix(attachment menu): Update logic to identify attachment menu page

---

.github/workflows/test.yml
CHANGES.md
karma.conf.js
package.json
spec/ContentDelegateSpec.js
spec/PacerSpec.js
src/content.js
src/pacer.js
src/utils.js

Fix [239](https://github.com/freelawproject/recap/issues/249)
PR addresses issues related to the docket report when it's accessed using the 'Reports' option in CM/ECF 1.6 and 1.7
Currently, the extension is not able to identify the page because the pacer_case_id is not part of the URL when the report loads.  The **case_id** is stored as the value of a hidden input with the id '**all_case_ids**' and changes when the user interacts with a text input used as a search bar for cases. 
The extension doesn't have the logic to listen to the changes being made to this value, so even when the **case_id** is inserted after the user specified a **case number**, the extension won't show the notice saying whether we have that docket or upload it. 
This PR adds a **listener** to the text input used as a …

fix(docket report): Update logic to detect docket report 

---

CHANGES.md
spec/ContentDelegateSpec.js
src/content_delegate.js
src/options.html

This PR solves multiple issues related to the links inserted by the RECAP extension:
- Avoid creating links that redirect to storage.courtlistener.com:
The links inserted by the extension go to [www.courtlistener.com](http://www.courtlistener.com/), which redirects to `storage.courtlistener.com`. This PR will change the links used in the href of the anchor tags to avoid redirection.  
- Remove the option to use a popup before opening RECAP documents
The current implementation of the extension has a check box on the options page that says, "Confirm before opening RECAP documents". If it's checked( which it is by default) it pops up a modal whenever you click an [R] icon to download a document. This PR fixes [#216](https://github.com/freelawproject/recap/issues/216) by removing all the …

fix(recap popup): Remove recap popup and update anchors href

---

CHANGES.md
spec/ContentDelegateSpec.js
spec/PacerSpec.js
src/pacer.js

This PR fixes https://github.com/freelawproject/recap/issues/222
The current implementation of the isDocketQueryUrl function only matches URLs that have a query string with only digits. That was fine, but the link from the appellate pacer to the original case has a different query string that includes the caseNumber parameter, so doesn't match properly in that case. 
The new regex expression will match both cases. Here's a gif showing that the extension will be able to insert banners in the `DktRpt.pl` after following the link in the appellate pacer.

fix(links from appellate): Makes isDocketQueryUrl more generic

---

.git-blame-ignore-revs
spec/AppellateSpec.js
spec/ContentDelegateSpec.js
spec/PacerSpec.js
spec/RecapSpec.js
src/action_button.js
src/appellate/appellate.js
src/appellate/utils.js
src/content_delegate.js
src/pacer.js
src/recap.js

This PR adds support for the attachment page from Appellate PACER to the RECAP extension.
This PR will introduce the following changes:
- This PR adds a new parameter called **upload_type** to the **uploadAttachmentMenu** method. The current implementation of this method only uploads attachment pages from district PACER.  This new parameter will allow us to use the same function to upload attachment pages from appellate PACER.
-  A new method to get the `Servlet` parameter will be added. This new method will use hidden `inputs` on the page to get it.
- This PR will refactor the  **dispatchHandler** method. The new method to get the Servlet parameter will allow us to easily identify the **case selection page**.
- The current implementation of the `AppellateDelegate` class is not able to …

feat(attachment page): Add support for attachment page from Appellate PACER

---

src/appellate/appellate.js

This PR will update the appellate class to insert the RECAP email banner in the **Case Search Page**. Here are some screenshots: 
The changes included in this PR will resolve https://github.com/freelawproject/recap/issues/313

feat(appellate): Update AppellateDelegate class to add RECAP email banners.

---

CHANGES.md
spec/RecapSpec.js
src/appellate/appellate.js
src/appellate/utils.js
src/content_delegate.js
src/pacer.js
src/recap.js
src/toolbar_button.js

This PR adds support to identify and upload the caseQueryAdvanced page from Appellate and District PACER. 
This PR will introduce the following changes:
- This PR will add new upload types to the `upload_types `array in the recap class.  These new types are `CASE_QUERY_RESULT_PAGE` and  `APPELLATE_CASE_QUERY_RESULT_PAGE`.
- A new parameter called `upload_type` will be added to the uploadIQueryPage method. The current implementation of this method only uploads **query pages** from district PACER.  This new parameter will allow us to use the same function to upload **CaseQueryAdvanced** from district PACER and **caseQuery** pages from appellate PACER.
- This PR will add new helper functions to identify the **CaseQueryAdvanced** page. These helpers use HTML elements to detect this page …

feat(caseQueryAdvanced): Add support to identify this page from PACER

---

src/appellate/appellate.js
src/recap.js

This PR adds support to upload case query pages from appellate PACER to the RECAP Archive.  This PR resolves https://github.com/freelawproject/recap/issues/317
- Adds a new upload type to the RECAP class.
- Updates the dispatch page handler in the Appellate class to include pages with the `servlet` parameter set to `'CaseQuery.jsp`'.
- Adds a new method to the Appellate class to upload the case query pages.

feat(appellate): Upload case query pages to RECAP

---

CHANGES.md
src/appellate/utils.js

This PR fixes https://github.com/freelawproject/recap/issues/324 implementing the suggested solution.

fix(doc links): Add the caseId parameter to doc links in Appellate Pacer

---

src/assets/css/style.css

This PR fixes the broken icons in the setting dialog and the spinner in the docket report page in Firefox. This PR resolves https://github.com/freelawproject/recap/issues/326.

fix(style): Fix broken icons in Firefox

---

CHANGES.md
spec/ContentDelegateSpec.js
src/appellate/appellate.js
src/content.js
src/content_delegate.js
src/pacer.js

This PR removes the checks using the PACER cookie, adds a new helper method to identify the login page, and updates the tests that use the cookie. This PR resolves https://github.com/freelawproject/recap/issues/325
I also noticed that the extension should do something when the user gets shown the `form` from the **case search page**  in the **case selection page**. The extension is returning early in cases like this but it seems like the extension is not working properly, so I think We should insert the recap email banner on this page.
Here's a gif showing how the current implementation handles the previous case:
Here's a gif with the changes from this PR:

fix(content.js): PACER cookie disables the extension

---

.git-blame-ignore-revs
spec/PacerSpec.js
spec/RecapSpec.js
src/appellate/appellate.js
src/appellate/utils.js
src/content.js
src/content_delegate.js
src/pacer.js
src/recap.js

this PR resolves https://github.com/freelawproject/recap/issues/21.
This PR includes the following changes:
- This PR adds two new helper methods to make **core docket numbers**. The first helper converts en & em dashes to hyphens, and it's called `normalizeDashes`, the other method makes a **core docket number** from an existing docket number, and it's called `makeDocketNumberCore`. This PR also adds tests for these methods.
- A new parameter is added to the getAvailabilityForDocket method. This new parameter is called core_docket_number and allows us to filter dockets using the `pacer_case_id `or the `docket_number_core`.
- This PR removes the `findAndStorePacerDocIds` method from the ContentDelegate class constructor. This method is asynchronous, so we should wait until it finds the …

feat(appellate): Reference district cases from Appellate

---

src/options.html
src/options.js

This PR adds review links to the last tab of the extension and resolves https://github.com/freelawproject/recap/issues/286.
This PR includes the following changes:
- This PR changes the name of the last tab in the extension Popup from **"Donate"** to **"Help RECAP"**.
- The donate button is aligned with the amount input.
- A new section is added in the last tab. This new section asks users for reviews and includes a link to the web store. This PR adds some code to detect the browser name and shows a different link depending on which browser is being used.
- The extension will use the link to the **Chrome Web Store** in **Microsoft Edge**.
Here's a picture of the tab in different browsers 
**Google Chrome - version 108.0.5359.125**
**Firefox - 108.0.1 (64-bit)**
**Microsoft Edge - version …

feat(options): Add review links to the last tab of the Extension

---

src/action_button.js
src/appellate/appellate.js
src/content.js

This PR fixes https://github.com/freelawproject/recap/issues/328
- This PR removes the mutation observer that allows us to watch for changes made to the childlist of the table element. This approach to add an `onClick` event to the **Recap Actions** button works only for district court pages. The mutation observer fails in Appellate pages because the HTML structure is different and the **RECAP actions** button is inserted in a different table.
- This PR adds an `onClick` event to the **Refresh links** button right after the extension creates it. The event handler removes the RECAP icons, shows the spinner, and invokes the `addRecapInformation` method. This new approach fixes the Refresh button for appellate pages because the extension is not …

fix(appellate): Refresh link not working in Appellate pages

---

CHANGES.md
spec/AppellateSpec.js
spec/PacerSpec.js
src/appellate/appellate.js
src/appellate/utils.js
src/background.js
src/pacer.js
src/pdf_upload.js
src/utils.js

This PR adds support to upload free documents from Appellate PACER. This PR resolves https://github.com/freelawproject/recap/issues/322.
- This PR adds three helper methods to get data related to document links:
- `getDocNumberFromAnchor`: This helper method gets the **document number** from the anchor element that has a document link.
- `getAttachmentNumberFromAnchor`: This utility function accesses the row that contains the document link and gets the **attachment number**.
- `cleanDocLinkNumber`: this helper function removes whitespace from the **document number** and the **attachment number**.
- The `findDocLinksFromAnchors` helper method from the `appellate utils` is updated to add an `onClick` event to every document link. This event allows …

feat(appellate): Upload free documents Apellate PACER

---

src/appellate/appellate.js
src/appellate/utils.js
src/pacer.js

This PR resolves https://github.com/freelawproject/recap/issues/327.
This PR includes the following changes:
- This PR will update the if statement in the `getAttachmentNumberFromAnchor` method to avoid looking for an attachment number if the row has 3 or fewer children nodes. The current implementation uses the `<` which fails if the row that contains the doc links has exactly 3 children nodes ( The table from the docket report has exactly 3 data cell elements but we don't want to search the attachment number in that table).
- This PR adds the `attachment number` to the doc links URL if it's found on the page and also makes sure that the `caseId `is always added to the href attribute.
- We add a new if statement to check the queryparameters

fix(attachment page): Add missing attachment number in Appellate

---

src/appellate/utils.js

This PR removes the namespace we added in [#308](https://github.com/freelawproject/recap-chrome/pull/308) to the `caseId` parameter. 
We should avoid changing this parameter name because **PACER** is using it to get more information about the **docket entry** associated with the document, We added this parameter to fix https://github.com/freelawproject/recap/issues/324.

fix(appellate utils): Remove namespace of the caseId parameter

---

CHANGES.md
spec/ContentDelegateSpec.js
spec/RecapSpec.js
src/assets/css/style.css
src/content_delegate.js
src/pacer.js
src/recap.js
src/utils.js

This PR resolves https://github.com/freelawproject/recap/issues/190.
- A new field is added to the `getAvailabilityForDocket` request. This PR adds the `date_last_filing` field to the list of dynamically selected fields.
- This PR adds two helper functions in the utils.js file. 
- `pacerDateFormat`: takes a date and returns it in 'MM/DD/YYYY' format
- `recapAddLatestFilingButton`: creates the HTML button that is inserted on the page and also creates an onClick event listener for this object. This utility function uses the `date_last_filing` from the response of `getAvailabilityForDocket` request to create a data attribute in the button.
- This PR adds CSS classes to change the styling of the new button.
- The helper method called `removeBanners` …

feat(district): Add button to autofill docket query form

---

CHANGES.md
spec/ContentDelegateSpec.js
src/appellate/appellate.js
src/appellate/utils.js

This PR fixes https://github.com/freelawproject/recap/issues/330.
-  This commit adds a new helper function called `getDocketNumber`. This new helper uses different approaches to get the docket number from the appellate pages.
- A new URL query parameter is added to the anchor's href attribute. This new query parameter is called `recapCaseNum`. This new parameter will be used as the last resource to get the docket number from an appellate page.
- This PR updates the methods `handleCaseSelectionPage`, `handleCaseQueryPage`, `attachRecapLinksToEligibleDocs`, `handleDocketDisplayPage` and `handleSingleDocumentPageView` from the AppellateDelegate class to save the docket number to the tab storage.
- Update the helper method called `getCaseId` to check …

fix(appellate): Avoid uploading case summary with the wrong case_id

---

CHANGES.md
safari/build-safari.py
src/InjectManager.js
src/appellate/appellate.js
src/assets/css/style-ios.css
src/assets/css/style.css
src/background.js
src/manifest.json
src/utils.js

This PR fixes issues that We found in Safari and resolves https://github.com/freelawproject/recap/issues/332. 
- We use a new approach to create the content of the banners. The current implementation of the extension creates a banner with a broken icon in safari so in order to fix that We're adding a helper function called `makeMessageForBanners`, this utility method creates the content of the banner and returns a `div` element.
- This PR updates the file called `style-ios.css`. This file has all the CSS classes that are used to build the extension that is going to be installed on iPhones.
- We're now injecting the content scripts using the background.js file to avoid **duplication**. This issue seems to be pretty common because Safari injects …

Fix broken icon in iOS

---

safari/APPLE.md
safari/build-safari.py
safari/resources/recap-iOS.html
safari/resources/recap-macOS.html

I've added the release notes for safari and also updated `build-safari.py` after removing the `!` from the name, also updated the splash screens for ios and mac to match the new app name "RECAP Uploader".

Safari release notes and updated build-safari.py

---

src/appellate/utils.js
src/utils.js

Be clear when we modify links in a webpage, by adding two markers.
Specifically, change two attributes:
* Add a `data-recap` attribute explaining that it was modified, and
* Append `recap_modified` to the CSS class list.
Resulted from a Slack discussion this morning in light of #324 where it was not obvious upon inspection that the RECAP extension was messing with the page and breaking the URL, and it would have aided debugging to have done so.
I don't quite understand the test infrastructure and where to add a test to check this stuff -- it seems like there's zero test coverage for `addCaseIdToDocketSummaryLink()` and I don't know quite where to begin, so no tests.
As a prereq, consistently use the `.dataset` API rather than rolling our own.

Be clear when we modify links in a webpage, by adding two markers.

---

src/appellate/utils.js

CA9 and CA2 both use ACMS for some dockets (**Edit: not just** immigration), which are hosted on an external website with a different URL form. So we have this sort of thing:
with:
```html
<td>
<a href="https://ca2-showdoc.azurewebsites.us/23-6359" target="_blank">
23-6359
</a>
<br>
<a href="TransportRoom?servlet=CaseQuery.jsp&amp;cnthd=2026821867&amp;caseid=1002765&amp;csnum1=23-6359&amp;shorttitle=United+States+of+America+v.+Conde+%28Kone%29">
United States of America v. Conde (Kone)
</a>
&nbsp;
</td>
```
And the current code breaks that first `<a>` link by appending a bare `&caseId` to it, which is improper since there is no preexisting `?`, and results in a URL that doesn't work and breaks appellate PACER. Doh!
Fix this and a few other instances of URL handling in `utils.js`, thusly. …

appellate/utils.js: Use URLSearchParams() properly

---

spec/AppellateSpec.js
src/appellate/appellate.js
src/appellate/utils.js
src/pdf_upload.js

While I was going through the manual [QA-Testing](https://github.com/freelawproject/recap/wiki/QA-Testing) list, I noticed the extension was not uploading free docs from appellate courts. I debugged the code and realized the `handleFreeDocResponse` method was failing because it wasn't getting the data attributes from the anchors. I remembered We tweaked the style of some of those attributes in #325, so this PR tweaks the naming style of the remaining data attributes and fixes the bug with the handleFreeDocResponse method.

fix(appellate): Tweak the utility function that upload free documents

---

CHANGES.md
spec/ContentDelegateSpec.js
spec/PacerSpec.js
src/appellate/utils.js
src/content_delegate.js
src/pacer.js

This commit fixes cases iii and iv from https://github.com/freelawproject/recap/issues/341.
- Adds a new utility function that only matches `doc1` URLs. This new helper function allows us to filter out all the `show_doc.pl` links on the reports before the extension tries to extract the `pacer_doc_id`.
- Add tests for the method called` isDoc1Url`.
- Updates the docstring for the `isDocumentUrl` method.

feat(pacer): Filter out show_doc links

---

CHANGES.md
src/content.js

This commit tweaks the logic to check the value of the hidden input with the id 'all_case_ids' before updating the `pacer_case_id`.
We checked this input in https://github.com/freelawproject/recap-chrome/pull/273 and found that it was empty when there wasn't a cookie for the case number ( here's a comment about it: https://github.com/freelawproject/recap-chrome/pull/273#pullrequestreview-1184750272) but I noticed that the input could also use `value='0'`, so the extension updates the `pacer_case_id`, tries to lookup a case using the API and it also creates a banner in the **Docket Query Page** linked to this [case](https://www.courtlistener.com/docket/66992224/united-states-v-sandoval/) but the user hasn't search any case.
Here's a screenshot of this bug:

feat(content.js): Tweak logic to get the pacer_case_id from input

---

spec/PacerSpec.js
src/pacer.js

Fixes [#244](https://github.com/freelawproject/recap/issues/244).

Add support for audio file PDFs and alternate transcript receipt format

---

CHANGES.md
spec/ContentDelegateSpec.js
src/utils.js

This PR updates the naming style of the attribute that stores the date in the autofill button and tweaks the tests to check we're using the right attribute name.
This PR fixes https://github.com/freelawproject/recap/issues/344

fix(utils): Fix broken autofill button

---

CHANGES.md
package.json
src/manifest.json

Fixes https://github.com/freelawproject/recap/issues/345

feat(packaging): Do release

---

src/pacer.js

The existing match conditions for attachment pages doesn't seem to be reliable(ie for example on `cacd`), lets just add a match condition for the "Document Selection Menu" text at the top as well which seems to fix these issues.

Improve Document Selection Menu page matching

---

spec/AppellateSpec.js
src/appellate/appellate.js
src/appellate/utils.js

This PR adds logic to normalize the document number when the appellate court uses the pacer_doc_id instead of the regular docket entry numbering.

fix(appellate): Normalize document number and dls_ids

---

CHANGES.md
spec/AppellateSpec.js
src/appellate/utils.js

While going through the QA steps, I realized the extension failed to upload free documents. After debugging the code, I noticed we're using the pacer_dls_id attribute in the [onClickEventHandlerForDocLinks](https://github.com/freelawproject/recap-chrome/blob/main/src/appellate/utils.js#L210) to create the request that allows us to check whether the doc link returns an HTML page (the view document page) or a pdf file (when it's free). sending the normalized version of the dls_id always returns an HTML page even when the doc is an opinion (which is a free doc).
This PR removes the logic to normalize the `dls_id.`

fix(appellate): Remove the logic to normalize the pacer_dls_id

---

CHANGES.md
src/background.js

This PR fixes https://github.com/freelawproject/recap/issues/346.
The current implementation of the extension inserts scripts listed in the `CONTENT_SCRIPT_FILES` array calling the `executeScripts` method sequentially inside a for-loop. I think this approach is causing the bug in Firefox because the  `executeScript` is an asynchronous function, so there may be calls that are still running when the next one starts (which is not desired). 
We need to make sure the extension injects a new script after the previous one succeeds and so on. Luckily we can pass a callback function`executeScripts` method so we can nest the `executeScript` calls like this:
```
chrome.tabs.executeScript(null, { file: "jquery.js" }, function() {
chrome.tabs.executeScript(null, { file: "master.js" }, function() { …
```

fix(background): Tweak logic to inject script programmatically

---

CHANGES.md
src/appellate/appellate.js
src/content.js
src/content_delegate.js
src/pacer.js
src/utils.js

This PR fixes https://github.com/freelawproject/recap/issues/337.
Here are screenshots of the new warning:
- **District courts:**
- **Appellate courts:**

feat(pacer): Adds warning about combined pdfs

---

CHANGES.md
src/pacer.js
src/toolbar_button.js

This PR adds a helper method to identify ACMS URLs and logic to show a warning sign in the toolbar icon when users are on those new websites.
Here's a screenshot of the toolbar icon:

feat(toolbar): Show warning sign in ACMS websites

---

CHANGES.md
src/content_delegate.js

This PR fixes https://github.com/freelawproject/recap/issues/352 by tweaking the `extractUrl` method to retrieve the URL from the `script` tag. During the debugging process, I noticed the absence of a message indicating that the extension was uploading the zip file. To address this, I added a loading message on the page to inform users that the extension is working on the upload task.
Here's a GIF showing the new message:
I couldn't reproduce the issue on Windows, it seems specific to macOS.

fix(content_delegate): Fix zip upload in district courts

---

src/content_delegate.js

During QA testing, I discovered that the zip upload feature was failing in **Firefox** and displaying an error message indicating that the extracted URL from the response was invalid. Further investigation revealed a known issue with Firefox's handling of relative URLs. To resolve this issue, we should employ absolute URLs instead of relative ones.
Here’s the Firefox issue [#2647](https://github.com/greasemonkey/greasemonkey/issues/2647).
Once this PR is merged, We'll be ready to release a new version containing the fix for ZIP uploads.

feat(content_delegate): Use the URL constructor to return absolute URL

---

CHANGES.md
src/appellate/utils.js

Seems some appellate court attachment pages aren't getting detected so lets add a fallback.

Add additional appelate attachment page detection logic

---

src/assets/css/style-ios.css
src/assets/css/style.css

This PR implements a fix for broken icons encountered in Safari 17.2 and Firefox 120.0.1.

fix(style): Tweaks the src attribute to display icons properly

---

CHANGES.md
src/assets/css/style.css

This simple CSS tweak should hide all the elements that we add, as long as they start with a CSS class or ID of `recap-*`. I haven't used the extension enough to be able to tell if this catches everything, but in my casual tests, it hid all the UI elements I could find.
If we discover any that are missed, we should probably just add a `.recap-blahblah` class to them.

Hide UI recap-* UI elements from printed pages

---

CHANGES.md
src/options.html

Updated the donation tab per https://github.com/freelawproject/recap/issues/359
The link goes to https://donate.free.law/forms/supportflp

Donation tab update

---

CHANGES.md
spec/ContentDelegateSpec.js
src/appellate/appellate.js
src/assets/css/style.css
src/content_delegate.js
src/utils.js

This PR fixes https://github.com/freelawproject/recap/issues/357
This is how the new button looks on different pages:
Single Document Page (District): 
Download Zip Page (District): 
Single Document Page (Appellate):

feat(receipt page): Add extra button for filer accounts

---

src/options.html

Currently, the newsletter icon in the extension links to https://free.law/newsletter/ which is a 404. The /newsletter page appears to have been deleted and replaced in [this commit](https://github.com/freelawproject/free.law/commit/fbf845aee7d8fe59dbb9bfe375379d0e21f9087b) last month.
This PR updates the newsletter icon link to go https://donate.free.law/np/clients/freelawproject/subscribe.jsp?subscription=9 which is the same location as the footer on https://free.law.
Newsletter icon in the extension:
How https://free.law/newsletter/ currently appears:

fix(options): Update newsletter link

---

CHANGES.md
src/assets/css/style.css
src/background.js
src/options.html
src/options.js
src/toolbar_button.js

This PR fixes https://github.com/freelawproject/recap/issues/367 by adding a badge to the extension icon in the toolbar and a new banner in the extension popup. 
Here's a screenshot of the new banner: 
Here's a GIF showing how the close icon works:
I created this PR as a draft because we still need the URL for the 'Learn More' button :).

feat(toolbar): Adds a banner and a badge for the PACER class action news

---

CHANGES.md
src/toolbar_button.js

Fixes:
```js
Error: Type error for parameter details (Property "text" is required) for browserAction.setBadgeText.
```

Fix setBadgeText type error

---

src/options.html

This PR adjusts the spacing of the header element within the popup window. In a previous PR (#368), we removed the HTML elements of the old banner but forgot to update the corresponding CSS class that sets the header height.

fix(popup): Adjust header spacing in popup window

---

.git-blame-ignore-revs
CHANGES.md
src/recap.js

This PR introduces a new upload type for Dockets from ACMS(`'ACMS_DOCKET_JSON': 16`) and enhances code maintainability by refactoring common upload logic into reusable functions.
This PR also enforces code style in the `recap.js` file using ESLint.

feat(recap): Adds new upload type for ACMS dockets

---

CHANGES.md
spec/AppellateSpec.js
spec/ContentDelegateSpec.js
spec/RecapSpec.js
src/appellate/acms_api.js
src/appellate/appellate.js
src/appellate/utils.js
src/background.js
src/manifest.json
src/pdf_upload.js
src/recap.js

This PR adds support to upload documents from the new ACMS website and inserts a banner that lets users know a matching record is available in the RECAP archive.
The PR introduces the following changes:
- Refines the `dispatchHandler` method to effectively manage the **Download confirmation page**. The extension uses the `path` property for page identification.
- Uses the [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) interface to monitor DOM changes and ensure all elements are rendered before proceeding. This PR removes the default `onclick` event of the **"Accept Charges"** button and replaces it with a custom event handler that allows us to upload documents to the RECAP archive.
- The Appellate class uses the ACMS API to retrieve the pdf documents …

feat(acms): Adds helper method to handle the Download Confirmation Page

---

CHANGES.md
src/appellate/appellate.js

This pull request introduces new methods for inserting the recap icon next to docket entry links whenever the corresponding document is accessible in the Recap archive and the RECAP button. The new helper functions are incorporated into the handleAcmsDocket method to use the existing mutationObserver and avoid repetition.
Here's a GIF showing the button and [R] icons:

feat(acms): Adds RECAP links and the RECAP button

---

CHANGES.md
src/appellate/appellate.js
src/recap.js

This PR introduces a new upload type for attachment pages from ACMS('ACMS_ATTACHMENT_PAGE': 17) and adds a new method `handleAcmsAttachmentPage` to the `AppellateDelegate` class specifically for handling attachment pages uploads from ACMS.
This PR depends on https://github.com/freelawproject/courtlistener/pull/3393.
Here's a gif showing how the extension works:

feat(acms): Adds support to upload ACMS attachment pages

---

CHANGES.md
src/appellate/appellate.js
src/assets/css/style.css
src/utils.js

This PR adds logic to check the number of documents on the download page and display the warning about combined PDFs when there's more than one.

feat(acms): Adds logic to display the warning about combined PDFs

---

CHANGES.md
spec/PacerSpec.js
src/pacer.js

This PR fixes https://github.com/freelawproject/recap/issues/371 by checking the `filingCookie` variable before accessing its value. I also added tests to ensure the fix works as expected and prevent regressions in the future.

fix(pacer): Prevents error by checking filingCookie existence

---

CHANGES.md
src/background.js
src/options.js
src/toolbar_button.js

This PR addresses a few issues related to the badge introduced in #379, specifically for Safari. 
While running the QA steps, I found the following issues:
- Safari doesn't render emojis inside the badge like Firefox and Chrome.
- Badge background color customization is not supported. It's always red. This issue is documented in the MDN web docs, here's the link: [setBadgeBackgroundColor()-Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setBadgeBackgroundColor#browser_compatibility)
- The current approach to remove the badge after users close the popup window is not working in Safari. This issue is also reported here: https://github.com/lapcat/SafariExtensions/issues/40
- Adds logic to …

feat(toolbar): Adds custom badge for Safari

---

CHANGES.md
src/pacer.js

While debugging https://github.com/freelawproject/recap/issues/373, I noticed pacer has 2 different login pages. One for the manage account page and another one to access pacer. Here are the URLs:
- https://pacer.login.uscourts.gov/csologin/login.jsf
- https://pacer.psc.uscourts.gov/pscof/login.xhtml
This PR refines the `isLoginPage` helper function to correctly detect both the standard and manage account login pages. It achieves this by employing a more specific approach checking the path.
After merging this PR, the extension will insert the banner in both login pages:
Also, this PR fixes https://github.com/freelawproject/recap/issues/373

feat(pacer): Enhance isLoginPage to accurately identify login pages

---

CHANGES.md
src/toolbar_button.js

This PR removes the logic that identified ACMS websites and displayed a warning icon indicating they are not supported.

feat(toolbar): Removes the warning icon for ACMS website

---

src/appellate/appellate.js

This PR fixes the MutationObserver function responsible for identifying ACMS download pages
In https://github.com/freelawproject/recap-chrome/pull/376, We introduced logic to check the number of documents on the download page and display a warning for combined PDFs. This code relied on data stored in `sessionStorage`. However, the key used to access this data is only set when the receipt page is loaded from an attachment page.
This PR addresses this limitation by implementing an additional check. This code makes sure the `MutationObserver` function continues to work correctly for receipt pages accessed from the docket summary.

fix(appellate): Adds logic to check for 'selectedDocuments' key

---

CHANGES.md
src/manifest.json

This PR updates the manifest file to implement a least privilege approach for permissions on Azure Websites. We're replacing the use of `include_globs` with a more granular approach that explicitly defines every single identified URL combination.
This change addresses concerns about overly broad permissions previously granted by the `matches` property. 
Fixes https://github.com/freelawproject/recap/issues/374
Here are screenshots showcasing the revised permission list. Notably, the option granting access to all Azure Websites sites is no longer included.

fix(manifest): Refines content_scripts permissions on azure websites

---

scripts/build.sh
src/manifest.json

This PR addresses the recent comment on issue [#333](https://github.com/freelawproject/recap/issues/333) regarding the warning encountered in Firefox. I noticed this warning message is still appearing when loading `.zip` files generated by the `build` script.
Following the [Firefox-specific migration checklist](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/), this PR renames the deprecated `applications` key in `manifest.json` to the new `browser_specific_settings` key.
This PR also updates the `build` script to remove the `browser_specific_settings` key from chrome release packages.
This change has been tested locally and the warning no longer appears during Firefox builds.

feat(manifest): Rename `applications` key to `browser_specific_settings`

---

CHANGES.md
safari/build-safari.py
src/utils/background_notifier.js

This PR addresses the following issues: 
- **Updates the script that creates the MacOS and iOS version of the extension**: After updating the manifest file to include new API permissions, the `update_manifest_files` helper method was overwriting the existing permissions for the macOS and iOS versions of the extension with a hardcoded list(This caused compatibility issues). The PR removes the hardcoded permissions list from the helper method, ensuring that the same set of permissions is used across all browsers.
- While testing the extension, I noticed that the code that creates notifications was consistently raising exceptions.  Investigating the [Notifications API documentation ](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/create), I realized …

fix(safari): Resolve manifest upgrade compatibility issues

---

CHANGES.md
src/action_button.js
src/appellate/appellate.js
src/assets/css/style.css
src/content_delegate.js
src/utils.js

This PR addresses comments from [Issue #361](https://github.com/freelawproject/recap/issues/361) and enhances user experience for file accounts:
- Implements a visual loading indicator (spinner) next to the custom button for filer accounts, providing feedback during PDF retrieval retries.
- Updates the styling of the recap-bttn-for-filers class to include a pointer cursor, improving user interaction clarity.
Here are gifs showcasing these visually updated elements in appellate and district courts:

feat(spinner): Adds spinner next to the custom button for filer accounts

---

src/content.js
src/options.html
src/options.js
src/utils/toolbar_button.js

This PR removes the banner from the login page and updates the banner within the options page to inform users about the code upgrade to Manifest Version 3. Additionally, it updates the badge icon style to use a number instead of the bell emoji for Firefox and Chrome.
Here are screenshots showing the banner and the badge icon:
-----
----

feat(toolbar): Enhance banners with updated content

---

CHANGES.md
src/utils/background_fetch.js

During QA testing for the upcoming extension release, I noticed that temporary upload data (files and zips) was not being removed from local storage after successful uploads. This issue could potentially lead to unnecessary storage usage and performance concerns.
This PR addresses the problem by tweaking the `triggerFetchRequest` method in `background_fetch.js`. The changes ensure that temporary data is consistently deleted from local storage once the upload process is complete.

feat(background): Adds logic to clean up storage after upload

---

CHANGES.md
scripts/build.sh

This commit fixes a typo in the path of the favicon file within release build script. The incorrect path was preventing the favicon from being rendered in the browser. By correcting the typo, the favicon will now be displayed as expected.
Fixes https://github.com/freelawproject/recap/issues/379

fix(scripts): Corrected typo in build script

---

CHANGES.md
spec/PacerSpec.js
src/content_delegate.js
src/pacer.js

key changes: 
- Updates the `parseGoDLSFunction` helper to accommodate new parameters present in district links.
- Adresses https://github.com/freelawproject/recap/issues/369 where PACER case IDs weren't reliably extracted on attachment pages by implementing suggestions outlined in https://github.com/freelawproject/recap-chrome/pull/398#issuecomment-2359524279 to enhance retrieval logic.

feat(district): Capture attachment pages with no footer form

---

CHANGES.md
src/content_delegate.js

This PR fixes https://github.com/freelawproject/recap/issues/366 by refining the `generateFileName` method to accurately compute zip file names, even for cases where the first document exceeds 30 pages. Previously, the logic lead to an error in such cases. This update addresses the issue by employing a more robust approach to compute the file name.
Here are some GIFs demonstrating the download functionality:
- Downloading Large Zip Files (Over 30 Pages):
- Downloading Smaller Documents (Under 30 Pages):

fix(district): Refine generateFileName method for large documents

---

CHANGES.md
spec/ContentDelegateSpec.js
src/appellate/appellate.js
src/content_delegate.js
src/pacer.js
src/utils/background_fetch.js

This PR fixes [#380](https://github.com/freelawproject/recap/issues/380) by replacing API calls to CourtListener with the latest v4 version, ensuring compatibility with the newest features and improvements.

feat(recap): Upgrade to CourtListener v4 API

---

CHANGES.md
src/utils/toolbar_button.js

This check needs to be before items is accessed.

Fix setDefaultOptions in updateToolbarButton

---

CHANGES.md
src/utils/background_notifier.js

The callers expect a response even if we don't actually show a notification.

fix(notifier): call sendResponse when notifications are disabled

---

.github/workflows/test.yml
CHANGES.md
src/utils/background.js

It seems firefox is picky here and won't accept the a `MAIN` string.

fix(background): use chrome.scripting.ExecutionWorld.MAIN for firefox compatibility

---

CHANGES.md
src/pacer.js

Looks like some of these(like ca1) have six elements.

Handle attachment number rows with six child elements

---

CHANGES.md
spec/AppellateSpec.js
spec/PacerSpec.js
src/appellate/appellate.js
src/appellate/utils.js
src/pacer.js

While assisting with the debugging of https://github.com/freelawproject/courtlistener/issues/3982, I noticed that a significant number of extension uploads originated from appellate courts. Upon investigating the underlying appellate helper functions, I discovered that some were using 0 as a default value, which leads to unexpected behavior.
This PR addresses this issue by updating the helper functions to use `null` as the default value instead of `0`.
Fixes https://github.com/freelawproject/recap/issues/382

fix(appellate): Avoids sending attachment number 0

---

CHANGES.md
src/appellate/appellate.js
src/appellate/utils.js
src/content_delegate.js
src/pdf_upload.js
src/utils.js

Key changes: 
- Refines the `handleCombinedPdfPageView` (appellate) and `handleCombinedPDFView` (district) methods to accurately identify multi-document pages containing only one PDF file. By analyzing the HTML structure, I noticed that receipt tables are enclosed within **center** divs, and the number of these **divs** corresponds to the number of files in the combined PDF.  Both methods now check for the presence of center nodes to determine if a warning should be displayed.
In appellate pages, an additional filter was implemented to ensure accurate counting, as center divs may also be used to wrap the page's main content.
- In both district and appellate courts, the document ID is often not directly accessible within the HTML structure of the page. While some courts use the document ID …

feat(pacer): Refine multi-document page handling logic

---

CHANGES.md
src/utils.js

This PR improves the reliability of banner insertion within the `checkSingleDocInCombinedPDFPage` function. The previous target element for **district courts**, now has the hidden attribute, which could interfere with banner display. This change addresses potential inconsistencies by switching the target element to the main div.

fix(utils): Improve Banner Insertion Reliability for regular users

---

CHANGES.md
karma.conf.js
src/appellate/appellate.js
src/appellate/utils.js

This PR adds a check to ensure that the `pacer_doc_id` is available before attempting to retrieve the PDF. If the `pacer_doc_id` is missing, the code will exit early to prevent unintended modifications to the page and incorrect `GET` requests.
This PR also updates the `karma.config.js` file to fix some failing tests 
Fixes https://github.com/freelawproject/recap/issues/388

feat(appellate): Adds guarding logic for missing pacer_doc_id

---

CHANGES.md
src/content_delegate.js
src/utils.js

This PR fixes  https://github.com/freelawproject/recap/issues/392: `docketNumber` values causing errors after viewing district court reports. Unlike appellate court reports, district court reports lack a consistent source for docket numbers, making extraction unreliable. Therefore, this commit clears the `docketNumber` from **localStorage** when a district court report is loaded, ensuring clean state and preventing unintended use of outdated data.

feat(district): Clears docketNumber from localStorage

---

.github/workflows/check_changelog.yml
CHANGES.md
src/options.html
src/utils/toolbar_button.js

Key changes:
- The banner in `options.html` is now hidden, and the header height has been adjusted. This ensures proper alignment of buttons and menu content, creating a clean layout.
- The default settings have been updated to hide the news badge on fresh installations.
fixes https://github.com/freelawproject/recap/issues/395

feat(options): Removes banner about manifest v3

---

src/options.html

PR #415 was supposed to hide the banner within `options.html`. However, while running the QA steps, I noticed the banner was still visible. Upon debugging, I discovered that the `d-flex` class was setting the display property, effectively overriding the `hidden` attribute.
It's possible a cached variable from a previous version of the extension was hiding the banner when I created PR #415, and this was cleared with the update. This PR also addresses and removes other classes that affect the `display` property.

fix(options): Removes conflicting display class to consistently hide banner
